### ISSUE TITLE
#1 - No se puede ingresar a la page

### ISSUE THREAD

**Issue by FacundoEG** [MarinaComotti/Desafio-final--Modulo-3--APX#1]
Hola Marina! Sabes que quería revisar el desafío pero cuando entro al link del readme la page no carga.

![20210919_170356](https://user-images.githubusercontent.com/79592789/133941474-cad74bbf-5dcb-4e57-bc07-9ea8c78fb697.png)

Fíjate de revisar bien a la hora de subirlo a github pages! Si tenes algún problema avisame y te ayudo si?

Apenas lo soluciones hago la review!  
Saludos

**Comment by Marcosreuquen** [comment]
Buenas, Marina.
Ahí busqué en deployments y creo que hay un guión donde va una i. 
@FacundoEG  si querés chusmearlo está en https://marinacomotti.github.io/Desafio-final--Modulo-3--APX/

Lo que vi yo es que en resolución mobile se rompe un poco, creo que el breakpoint es muy bajo, capaz podrías subirle los px a 769 que es la resolución standard de las tablets y con eso se arreglaría. En formato desktop está excelente! 
Saludos!!

**Comment by FacundoEG** [comment]
@Marcosreuquen gracias por la data de los deployments

Marina ahí pude ingresar y revisar la page, en líneas generales te quedo muy bien! pero concuerdo con Marcos en que entre los 383px y los 785px (aprox) hay elementos que no responden bien y se rompen. Sugiero lo mismo, que cambies el breakpoint, como mínimo a un nivel del ancho que te permita contener todo bien.

Saludos!

**Comment by MarinaComotti** [comment]
Gracias por las devoluciones!! Ahí lo arreglo y lo vuelvo a mandar
